```{r}
#libs
library(plotly)
library(quantmod)
library(TTR)
library(tseries)
library(forecast)
library(glue)
library(dplyr)
```


```{r}
clean_data <- function(t){
    #load timeseries of stock using quantmod
    #t="pypl"
    eq_ts <- getSymbols(t,auto.assign = FALSE)
    eq_ts <- to.monthly(eq_ts)
    View(eq_ts)
    eq_ts <- to.weekly(eq_ts)
    eq_df <- data.frame(Date=as.Date(index(eq_ts)),coredata(eq_ts))
    #clean up column names
    tmpnames <- unlist(strsplit(colnames(eq_df),"\\."))
    colnames(eq_df) <- tmpnames[tmpnames!="eq_ts"]
    View(eq_df)
    #Create Bollinger Bands from TTR Package
    bbands <- BBands(eq_df[,c("High", "Low", "Close")])
    #Ignore Data older than 2 years
    cdate <- as.POSIXlt(Sys.Date())
    cdate$year <- cdate$year-2
    eq_df <- subset(cbind(eq_df, data.frame(bbands[,1:3])), Date >= as.Date(cdate))
    #Create univariate timeseries for arima modeling
    uv_ts <- eq_ts[,"eq_ts.Close"]
    #Use forecast package to create auto.arima and forecast development at different confidence levels
    eq_arima <- auto.arima(uv_ts)
    fc <- forecast(eq_arima, h=26, level=c(50,80,95))
    fc_df <- data.frame(fc)
    fc_df$Date <- c(Date=seq(Sys.Date(), by="weeks", length=27)[-1])
    eq_out <- merge(eq_df, fc_df,all=TRUE)
    return(eq_out)
}
View(fc_df)
  #df <- eq_out
  plot_ticker <- function(df){
    #plot the price
    plt_price <- df %>% 
      plot_ly(x=~Date, type="candlestick",
              open=~Open, close=~Close, 
              high=~High, low=~Low, name="PYPL",
              decreasing=list(color="#d66a60"), 
              increasing=list(color="#9bf2a2")) %>% 
      add_lines(y=~up, name="Bollinger Bands", line=list(width=0.25, color="#29C37B"), hoverinfo="none", showlegend=FALSE) %>% 
      add_lines(y=~dn, name="Bollinger Bands", line=list(width=0.25, color="#29C37B"), hoverinfo="none", showlegend=FALSE) %>% 
      add_lines(y=~mavg, name="Moving Avg", line=list(width=0.5, color="#29C37B"), hoverinfo="none") %>% 
      add_ribbons(ymin=~Lo.95, ymax=~Hi.95,   fillcolor="#d5e8e5", line=list(width=0.5, color="#b9c9c6")) %>% 
      add_ribbons(ymin=~Lo.80, ymax=~Hi.80,   fillcolor="#a0dbd0", line=list(width=0.5, color="#80b2a9")) %>% 
      add_ribbons(ymin=eval(parse(text=paste("~Lo.", toString(50), sep=""))), ymax=~Hi.50,   fillcolor="#7dd1c2", line=list(width=0.5, color="#5fb7a7")) %>% 
      add_lines(y=~Point.Forecast, name="Forecast", line=list(width=1, color="FF5733")) %>% 
      layout(yaxis=list(title="price"))
    
    #plot volume
    plt_vol <- df %>% 
      plot_ly(x=~Date, y=~Volume, name="Volume", type="bar", marker=list(color="#10acb5")) %>% 
      layout(yaxis=list(title="vol", tickfont=list(size=8)))
    
    #subplot
    plt_ts <- subplot(plt_price, plt_vol, heights=c(0.8,0.2), nrows=2, shareX=TRUE, titleY=TRUE) %>% 
      layout(title=paste("PYPL", " - ", Sys.Date()),
             legend=list(orientation="h",
                         xanchor="center", x = 0.5, y=1.5,
                         font = list(size = 5),
                         bgcolor = 'white'), showlegend=FALSE)
    plt_ts
    return(plt_ts)
  }
```



```{r}
plot_ticker(clean_data("PYPL"))

```

```{r}
class(getSymbols("aohj"))
a <- tryCatch(
  getSymbols("pypl"),
  error=function(e){return(1)},
  warning=function(w){return(10)}
)
```

```{r}
scrape_info <- function(t){
    tmp <- read_html(glue("http://www.nasdaq.com/symbol/{tolower(t)}")) %>% 
      html_nodes("#left-column-div div p")
    return(html_table(tmp, fill=TRUE)[[1]])
}
df <- scrape_info("pypl")
out <- data.frame(c("a","b"),c("d","e"))
out <- rbind(out, c("a", "b"))
out <- rbind(out, c("1Y Target", df$X2[2]))
out <- rbind(out, c("50D avg vol", df$X2[5]))
out <- rbind(out, c("Market cap", df$X2[8]))
out <- rbind(out, c("P/E ratio", df$X2[9]))
out <- rbind(out, c("EPS", df$X2[11]))
out <- rbind(out, c("Beta", df$X2[16]))
out <- data.frame(c("1Y Target","50D avg vol","Market cap","P/E ratio","EPS","Beta"), c(df$X2[2],df$X2[5],df$X2[8],df$X2[9],df$X2[11],df$X2[16]))
colnames(out)=c("name", "value")
View(out)
html_text(tmp)[2]

```

